/**
 * Database import — move a SQLite file into whichever database this server is
 * configured to use (docs/DENO-PORT.md §9).
 *
 * The case this exists for: the site ran locally on SQLite for a while, then
 * moved to a hosted Postgres, and every article, image row and account had to
 * be retyped. This walks the tables in a safe order and writes them into the
 * current target.
 *
 * Three things make it less trivial than `INSERT … SELECT`:
 *
 *   1. `images.collection_id` and `collections.cover_image_id` point at each
 *      other, so whichever table goes first cannot fill its column. Those two
 *      are inserted as NULL and patched by a second pass.
 *   2. Every `id` is `GENERATED BY DEFAULT AS IDENTITY`, which accepts explicit
 *      ids but leaves the sequence behind them, so the next API-created row
 *      would collide. The sequences are repaired at the end.
 *   3. `sessions` and `audit_logs` are optional: a session cookie from another
 *      install means nothing here, and audit history is often not wanted.
 *   4. Merge inserts explicit ids, so a row whose id, email or slug is already
 *      taken in the target is skipped rather than overwritten (`ON CONFLICT DO
 *      NOTHING`). Content is never lost — the new row simply is not added — but
 *      rows pointing at it keep pointing at whatever was already there, so the
 *      response counts every skipped row and warns.
 *
 * Nothing here ever writes to the file that was uploaded: it is copied to a
 * temp file, opened read-only, and removed again.
 */
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { DatabaseSync } from 'node:sqlite'

import { describeTarget, driverName, exec, get, run, tx } from './db.js'

/** Upload ceiling. Matches the `express.raw` limit mounted in index.js. */
export const MAX_BYTES = 25 * 1024 * 1024

/** Every SQLite file starts with exactly these 16 bytes. */
const SQLITE_MAGIC = 'SQLite format 3\u0000'

/** Rows per `INSERT` statement. Keeps the parameter count well under both limits. */
const BATCH = 50

/**
 * The tables we are willing to move, **in insert order**, with the columns that
 * exist in both schemas. Order is not cosmetic: every row below depends only on
 * tables above it.
 *
 * `defaultOn: false` means the table is offered but not ticked: see the note
 * about sessions and audit history in the file header.
 */
export const IMPORT_TABLES = [
  {
    name: 'roles',
    label: 'Roles',
    defaultOn: true,
    identity: false,
    columns: ['key', 'name', 'description', 'rank', 'is_system'],
  },
  {
    name: 'permissions',
    label: 'Permissions',
    defaultOn: true,
    identity: false,
    columns: ['key', 'group_key', 'description'],
  },
  {
    name: 'role_permissions',
    label: 'Role → permission links',
    defaultOn: true,
    identity: false,
    columns: ['role_key', 'permission_key'],
  },
  {
    name: 'users',
    label: 'People (includes password hashes)',
    defaultOn: true,
    identity: true,
    columns: [
      'id',
      'email',
      'name',
      'avatar_url',
      'password_hash',
      'role_key',
      'status',
      'wechat_openid',
      'wechat_unionid',
      'wechat_nickname',
      'wechat_avatar',
      'invited_by',
      'invite_token',
      'created_at',
      'updated_at',
      'last_login_at',
    ],
  },
  {
    name: 'sections',
    label: 'Sections (navigation)',
    defaultOn: true,
    identity: false,
    columns: ['key', 'label', 'kind', 'position', 'visible'],
  },
  {
    name: 'collections',
    label: 'Collections',
    defaultOn: true,
    identity: true,
    columns: [
      'id',
      'slug',
      'title',
      'section_key',
      'kind',
      'summary',
      'cover_image_id',
      'place',
      'year',
      'status',
      'position',
      'author_id',
      'published_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'images',
    label: 'Images (rows only — the files live on OSS)',
    defaultOn: true,
    identity: true,
    columns: [
      'id',
      'collection_id',
      'owner_id',
      'url',
      'thumb_url',
      'width',
      'height',
      'bytes',
      'format',
      'caption',
      'alt',
      'oss_provider',
      'oss_key',
      'status',
      'position',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'articles',
    label: 'Articles',
    defaultOn: true,
    identity: true,
    columns: [
      'id',
      'slug',
      'title',
      'section_key',
      'excerpt',
      'body',
      'cover_image_id',
      'status',
      'position',
      'author_id',
      'published_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'feed_items',
    label: 'Home slideshow',
    defaultOn: true,
    identity: true,
    columns: [
      'id',
      'image_id',
      'caption',
      'link_kind',
      'link_url',
      'target_collection_id',
      'target_article_id',
      'status',
      'position',
      'author_id',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'pages',
    label: 'Single pages',
    defaultOn: true,
    identity: true,
    columns: [
      'id',
      'slug',
      'title',
      'kind',
      'body',
      'data',
      'status',
      'author_id',
      'published_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'audit_logs',
    label: 'Activity log (history from the old install)',
    defaultOn: false,
    identity: true,
    columns: ['id', 'user_id', 'action', 'entity', 'entity_id', 'meta', 'created_at'],
  },
  {
    name: 'sessions',
    label: 'Sign-in sessions (useless across installs)',
    defaultOn: false,
    identity: false,
    columns: ['token_hash', 'user_id', 'created_at', 'expires_at', 'user_agent', 'ip'],
  },
]

/** Columns that cannot be filled until everything else is in place. */
const DEFERRED = [
  { table: 'collections', column: 'cover_image_id' },
  { table: 'images', column: 'collection_id' },
]

const BY_NAME = new Map(IMPORT_TABLES.map((table) => [table.name, table]))

/** True when `name` is one of the tables this importer knows. */
export function isKnownTable(name) {
  return BY_NAME.has(String(name))
}

/** The catalogue the UI renders: name, label and whether to pre-tick it. */
export function tableCatalogue() {
  return IMPORT_TABLES.map(({ name, label, defaultOn }) => ({ name, label, default: defaultOn }))
}

/** Table names to import when the request does not say. */
export function defaultTableNames() {
  return IMPORT_TABLES.filter((table) => table.defaultOn).map((table) => table.name)
}

/** Validate a caller-supplied table list against the allowlist. */
export function selectTables(names) {
  if (!names || !names.length) return IMPORT_TABLES.filter((table) => table.defaultOn)
  const wanted = new Set(names)
  return IMPORT_TABLES.filter((table) => wanted.has(table.name))
}

/** True when the buffer is a SQLite database file (not a gzip, not a CSV). */
export function isSqliteFile(buffer) {
  return (
    Buffer.isBuffer(buffer) && buffer.length >= 16 && buffer.subarray(0, 16).toString('latin1') === SQLITE_MAGIC
  )
}

/* ------------------------------------------------------------------- read -- */

/**
 * Read the selected tables out of the uploaded file.
 *
 * The bytes are written to a temp file first because `node:sqlite` only opens
 * paths, then opened **read-only** so a probe cannot touch the source. Missing
 * tables and missing columns are tolerated: an older database simply has less
 * in it.
 */
function readSource(buffer, selected) {
  const file = path.join(os.tmpdir(), `portfolio-import-${process.pid}-${Date.now()}.db`)
  fs.writeFileSync(file, buffer)

  let db
  try {
    db = new DatabaseSync(file, { readOnly: true })
    const present = new Set(
      db
        .prepare("SELECT name FROM sqlite_master WHERE type = 'table'")
        .all()
        .map((row) => String(row.name)),
    )

    return selected.map((table) => {
      if (!present.has(table.name)) {
        return { table, present: false, columns: table.columns, rows: [] }
      }
      const declared = new Set(
        db
          .prepare(`PRAGMA table_info(${table.name})`)
          .all()
          .map((row) => String(row.name)),
      )
      const columns = table.columns.filter((column) => declared.has(column))
      if (!columns.length) return { table, present: false, columns: [], rows: [] }
      const rows = db.prepare(`SELECT ${columns.join(', ')} FROM ${table.name}`).all()
      return { table, present: true, columns, rows }
    })
  } finally {
    try {
      db?.close()
    } catch {
      // closing a read-only handle cannot fail in a way that matters here
    }
    fs.rmSync(file, { force: true })
  }
}

/* ------------------------------------------------------------------ write -- */

/** SQLite hands back BigInt for large integers; the drivers want plain values. */
function cell(value) {
  if (value === undefined || value === null) return null
  if (typeof value === 'bigint') return Number(value)
  if (typeof value === 'boolean') return value ? 1 : 0
  return value
}

/** `(?, ?), (?, ?)` for a multi-row insert. */
function tuples(columnCount, rowCount) {
  const one = `(${Array.from({ length: columnCount }, () => '?').join(', ')})`
  return Array.from({ length: rowCount }, () => one).join(', ')
}

function chunk(rows, size) {
  const out = []
  for (let i = 0; i < rows.length; i += size) out.push(rows.slice(i, i + size))
  return out
}

async function count(table) {
  return Number((await get(`SELECT COUNT(*) AS n FROM ${table}`))?.n ?? 0)
}

/** Insert one table's rows, honouring merge vs replace and the deferred columns. */
async function insertTable(entry, deferredColumn) {
  const { table, columns, rows } = entry
  if (!rows.length) return 0
  const insertColumns = columns.filter((column) => column !== deferredColumn)
  const sql =
    driverName === 'postgres'
      ? `INSERT INTO ${table.name} (${insertColumns.join(', ')}) VALUES %VALUES% ON CONFLICT DO NOTHING`
      : `INSERT OR IGNORE INTO ${table.name} (${insertColumns.join(', ')}) VALUES %VALUES%`

  let inserted = 0
  for (const batch of chunk(rows, BATCH)) {
    const params = []
    for (const row of batch) {
      for (const column of insertColumns) params.push(cell(row[column]))
    }
    await run(sql.replace('%VALUES%', tuples(insertColumns.length, batch.length)), params)
    inserted += batch.length
  }
  return inserted
}

/** Second pass: fill the mutually-dependent columns now that both sides exist. */
async function backfillDeferred(source, deferred) {
  let patched = 0
  for (const { table, column } of DEFERRED) {
    if (!deferred.has(table)) continue
    const entry = source.find((item) => item.table.name === table)
    if (!entry?.present || !entry.columns.includes(column)) continue
    for (const row of entry.rows) {
      const value = cell(row[column])
      if (value === null || row.id === undefined) continue
      await run(`UPDATE ${table} SET ${column} = ? WHERE id = ?`, [value, cell(row.id)])
      patched += 1
    }
  }
  return patched
}

/** Postgres identity sequences to not know about the ids we just inserted. */
async function repairSequences(selected) {
  if (driverName !== 'postgres') return
  for (const table of selected) {
    if (!table.identity) continue
    // GREATEST(…, 1) because `setval` rejects 0, and the third argument keeps a
    // still-empty table handing out 1 on its next insert.
    await exec(
      `SELECT setval(pg_get_serial_sequence('${table.name}', 'id'), ` +
        `GREATEST(COALESCE((SELECT MAX(id) FROM ${table.name}), 0), 1), ` +
        `(SELECT COUNT(*) > 0 FROM ${table.name}))`,
    )
  }
}

/* ------------------------------------------------------------------ entry -- */

/**
 * Import `buffer` into the database this process is configured for.
 *
 * One transaction: if any table fails, nothing is applied and the caller sees
 * the reason. `dryRun` reads and counts but writes nothing, which is what the
 * Preview button in the UI sends.
 */
export async function importDatabase({ buffer, tables, mode = 'merge', dryRun = false }) {
  const started = Date.now()
  const selected = selectTables(tables)
  const source = readSource(buffer, selected)
  const warnings = []

  if (!selected.length) throw new Error('No tables selected')

  const selectedNames = new Set(selected.map((table) => table.name))
  const deferred = new Set(
    DEFERRED.filter((item) => selectedNames.has(item.table)).map((item) => item.table),
  )
  /** table name → the one column that must wait for a second pass. */
  const deferredColumnOf = new Map(
    DEFERRED.filter((item) => deferred.has(item.table)).map((item) => [item.table, item.column]),
  )

  const results = []

  if (dryRun) {
    for (const entry of source) {
      results.push({
        name: entry.table.name,
        label: entry.table.label,
        present: entry.present,
        read: entry.rows.length,
        existing: await count(entry.table.name),
        inserted: null,
        skipped: null,
      })
      if (!entry.present) warnings.push(`${entry.table.label}: not present in the uploaded file`)
    }
    return {
      mode,
      dryRun: true,
      target: describeTarget(),
      driver: driverName,
      tables: results,
      warnings,
      durationMs: Date.now() - started,
    }
  }

  await tx(async () => {
    if (mode === 'replace') {
      // Reverse order, so a table is emptied only after everything that points
      // at it. A `RESTRICT` failure here is the signal that the caller left a
      // referencing table out of the selection.
      for (const table of [...selected].reverse()) await run(`DELETE FROM ${table.name}`)
    }

    for (const entry of source) {
      const before = await count(entry.table.name)
      const attempted = await insertTable(entry, deferredColumnOf.get(entry.table.name) ?? null)
      const after = await count(entry.table.name)
      const inserted = after - before
      const skipped = attempted - inserted
      results.push({
        name: entry.table.name,
        label: entry.table.label,
        present: entry.present,
        read: entry.rows.length,
        inserted,
        skipped,
        attempted,
        existing: after,
      })
      if (!entry.present) warnings.push(`${entry.table.label}: not present in the uploaded file`)
      else if (inserted === 0 && attempted > 0) {
        warnings.push(`${entry.table.label}: every row already existed — nothing added`)
      } else if (skipped > 0) {
        warnings.push(
          `${entry.table.label}: ${skipped} of ${attempted} rows skipped — an existing row already used the same id, email or slug. Use replace if the uploaded copy should win.`,
        )
      }
    }

    const patched = await backfillDeferred(source, deferred)
    if (patched) warnings.push(`filled ${patched} circular reference(s) after insert`)

    await repairSequences(selected)
  })

  return {
    mode,
    dryRun: false,
    target: describeTarget(),
    driver: driverName,
    tables: results,
    warnings,
    durationMs: Date.now() - started,
  }
}
